name: CI

on:
  workflow_call: # From .github/workflows/Release.yml
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  # The purpose of running every night is to detect when a change to
  # https://github.com/rust-lang/rust/tree/master/src/rustdoc-json-types
  # requires that we release a new version of public-api to be compatible with
  # the latest nightly toolchain
  schedule:
    - cron: '33 3 * * *'

env:
  CARGO_TERM_COLOR: always

jobs:
  cargo-fmt:
    name: cargo fmt -- --check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cargo fmt -- --check

  cargo-doc:
    name: cargo rustdoc -- --deny warnings
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cargo rustdoc -- --deny warnings --locked --no-deps

  cargo-clippy:
    name: cargo clippy -- --deny clippy::all --deny clippy::pedantic ...
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cargo clippy --locked --all-targets --all-features -- --deny clippy::all --deny clippy::pedantic --deny dead_code

  cargo-test:
    name: cargo test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          profile: minimal
      - run: cargo test --locked

  test-invocation-variants:
    name: scripts/test-invocation-variants.sh
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          profile: minimal
      - run: scripts/test-invocation-variants.sh
