name: Release

on:
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  ci:
    uses: ./.github/workflows/CI.yml

  release:
    needs: ci
    environment: crates.io
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      # Figure out what tag to use. Do this first since we want to ensure that
      # the same tag is used for both public-api and cargo-public-api before we
      # start to cargo publish. Currently cargo publish does not support
      # publishing many crates at once. See
      # https://github.com/rust-lang/cargo/issues/1169.
      - name: calculate tag
        id: tag
        run: |
          version=$(cargo read-manifest --manifest-path public-api/Cargo.toml | scripts/pyjq.sh version)
          version2=$(cargo read-manifest --manifest-path cargo-public-api/Cargo.toml | scripts/pyjq.sh version)
          if [ "$version" != "$version2" ]; then
            echo "Version mismatch! Keep public-api and cargo-public-api versions in sync before you release! $version != $version2"
            exit 42
          fi
          echo ::set-output name=NAME::v${version}

      # Try to cargo publish public-api. If this succeeds we will tag the
      # release. This is because we don't want to have a situation where a
      # version exists at crates.io but not as a git tag.
      - run: cargo publish -p public-api
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}

      # Push the tag to git.
      - name: push tag
        run: |
          git tag ${{ steps.tag.outputs.NAME }}
          git push origin ${{ steps.tag.outputs.NAME }}

      # Now before we also create a GitHub Release, also try to cargo publish
      # cargo-public-api.
      - run: cargo publish -p cargo-public-api
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}

      # OK, both public-api and cargo-public-api has been published under the
      # same version. Create a GitHub Release now.
      - uses: softprops/action-gh-release@1e07f4398721186383de40550babbdf2b84acfc5 # v0.1.14
        with:
          tag_name: ${{ steps.tag.outputs.NAME }}
          generate_release_notes: true
